# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

User.destroy_all
Book.destroy_all
Shelf.destroy_all

User.create(username: 'guest', password: 'password1')
User.create(username: 'nat', password: 'password')

shelves = Shelf.create([
  { title: "Fantasy & Science Fiction", user_id: User.where(username: "nat")[0].id, description: "Lorem ipsum dolor
    sit amet, consectetur adipiscing elit. Phasellus gravida est tortor, quis varius
    augue sagittis in. Fusce et velit non lacus placerat vehicula."},
  { title: "Philosophy & Theory", user_id: User.where(username: "nat")[0].id, description: "Lorem ipsum dolor
    sit amet, consectetur adipiscing elit. Phasellus gravida est tortor, quis varius
    augue sagittis in. Fusce et velit non lacus placerat vehicula."},
  { title: "Goosebumps", user_id: User.where(username: "nat")[0].id, description: "Lorem ipsum dolor
    sit amet, consectetur adipiscing elit. Phasellus gravida est tortor, quis varius
    augue sagittis in. Fusce et velit non lacus placerat vehicula."},
  { title: "Harry Potter", user_id: User.where(username: "nat")[0].id, description: "Lorem ipsum dolor
    sit amet, consectetur adipiscing elit. Phasellus gravida est tortor, quis varius
    augue sagittis in. Fusce et velit non lacus placerat vehicula."},
  { title: "Fiction", user_id: User.where(username: "nat")[0].id, description: "Lorem ipsum dolor
    sit amet, consectetur adipiscing elit. Phasellus gravida est tortor, quis varius
    augue sagittis in. Fusce et velit non lacus placerat vehicula."}
])

books = Book.create([
  { title: "Goosebumps: Welcome to Dead House", author_fname: "R.L.", author_lname: "Stine", cover: "https://s3.amazonaws.com/shouldreads-dev/welcome+to+dead+house.jpeg", description: "They're baa-aack! The 25 most popular titles in the bestselling children's series of all time return w/ a fresh new look...to scare a new generation of readers. Reader beware--you're in for a scare!

Just when you thought it was safe....the 25 top-selling titles in the series that revolutionized horror for kids are back w/ a fresh new look. The updated design will make you scream. The original artwork will give you nightmares. And the classic bone-chilling stories from the master of horror will just kill you.
This spine-tingling series sparked a licensing phenomenon & made R.L. the #1 author in the U.S.--and it's STILL the must have collection for true horror fans. Now a whole new generation will discover the thrill of reading ...and they'll never be the same again."},
  { title: "Goosebumps: Attack of the Mutant", author_fname: "R.L.", author_lname: "Stine", cover: "https://s3.amazonaws.com/shouldreads-dev/attack+of+the+mutant.jpeg", description: "He's no superhero. He's a supervillain! Skipper Matthews has an awesome comic book collection. His favorite one is called The Masked Mutant. It's about an evil supervillain who's out to rule the universe! Skipper can't get enough of The Mutant. Until one day he gets lost in a strange part of town. And finds a building that looks exactly like The Mutant's secret headquarters. A building that appears and disappears! Has Skipper read one too many comic books? Or does The Masked Mutant really live in Riverview Falls?"},
  { title: "Goosebumps: The Girl who Cried Monster", author_fname: "R.L.", author_lname: "Stine", cover: "https://s3.amazonaws.com/shouldreads-dev/the+girl+who+cried+monster.jpeg", description: "When Lucy observes the summer librarian eating flies and turning into a grotesque creature, she is certain that he is a real, live monster. Original."},
  { title: "Goosebumps: The Night of the Living Dummy II", author_fname: "R.L.", author_lname: "Stine", description: "They're baa-ack! Make way for the bestselling children's series of all time! With a fresh new look, GOOSEBUMPS is set to scare a whole new generation of kids. So reader beware--you're in for a scare!

He's still walking.
He's still stalking.

Amy's ventriloquist dummy, Dennis, keeps losing his head -- for real. So Amy begs her family for a new dummy. That's when her dad finds Slappy in a local pawnshop. Slappy's kind of ugly, but at least his head stays on! And besides, Amy's having fun practicing her new routine. It's like this dummy knows what she's thinking. Like he can move on his own. And it's great - until Slappy starts a routine of his own. A nasty, horrible routine. And Amy can't control him....", cover: "https://s3.amazonaws.com/shouldreads-dev/night+of+the+living+dummy+II.jpeg"},
  { title: "Harry Potter and the Sorceror's Stone", author_fname: "J.K.", author_lname: "Rowling", description: "Harry Potter has never even heard of Hogwarts when the letters start dropping on the doormat at number four, Privet Drive. Addressed in green ink on yellowish parchment with a purple seal, they are swiftly confiscated by his grisly aunt and uncle. Then, on Harry's eleventh birthday, a great beetle-eyed giant of a man called Rubeus Hagrid bursts in with some astonishing news: Harry Potter is a wizard, and he has a place at Hogwarts School of Witchcraft and Wizardry. An incredible adventure is about to begin!", cover: "https://s3.amazonaws.com/shouldreads-dev/harry+potter+and+the+sorcerors+stone.jpeg"},
  { title: "Harry Potter and the Chamber of Secrets", author_fname: "J.K.", author_lname: "Rowling", description: "Harry Potter's summer has included the worst birthday ever, doomy warnings from a house-elf called Dobby, and rescue from the Dursleys by his friend Ron Weasley in a magical flying car! Back at Hogwarts School of Witchcraft and Wizardry for his second year, Harry hears strange whispers echo through empty corridors - and then the attacks start. Students are found as though turned to stone... Dobby's sinister predictions seem to be coming true.", cover: "https://s3.amazonaws.com/shouldreads-dev/harry+potter+chamber+secrets.jpeg"},
  { title: "Harry Potter and the Prisoner of Azkaban", author_fname: "J.K.", author_lname: "Rowling", description: "When the Knight Bus crashes through the darkness and screeches to a halt in front of him, it's the start of another far from ordinary year at Hogwarts for Harry Potter. Sirius Black, escaped mass-murderer and follower of Lord Voldemort, is on the run - and they say he is coming after Harry. In his first ever Divination class, Professor Trelawney sees an omen of death in Harry's tea leaves... But perhaps most terrifying of all are the Dementors patrolling the school grounds, with their soul-sucking kiss...", cover: "https://s3.amazonaws.com/shouldreads-dev/harry+potter+prisoner+azkaban.jpeg"},
  { title: "Harry Potter and the Goblet of Fire", author_fname: "J.K.", author_lname: "Rowling", description: "The Triwizard Tournament is to be held at Hogwarts. Only wizards who are over seventeen are allowed to enter - but that doesn't stop Harry dreaming that he will win the competition. Then at Hallowe'en, when the Goblet of Fire makes its selection, Harry is amazed to find his name is one of those that the magical cup picks out. He will face death-defying tasks, dragons and Dark wizards, but with the help of his best friends, Ron and Hermione, he might just make it through - alive!", cover: "https://s3.amazonaws.com/shouldreads-dev/harry+potter+goblet+fire.jpeg"},
  { title: "Harry Potter and the Order of the Phoenix", author_fname: "J.K.", author_lname: "Rowling", description: "Dark times have come to Hogwarts. After the Dementors' attack on his cousin Dudley, Harry Potter knows that Voldemort will stop at nothing to find him. There are many who deny the Dark Lord's return, but Harry is not alone: a secret order gathers at Grimmauld Place to fight against the Dark forces. Harry must allow Professor Snape to teach him how to protect himself from Voldemort's savage assaults on his mind. But they are growing stronger by the day and Harry is running out of time...", cover: "https://s3.amazonaws.com/shouldreads-dev/harry+potter+order+phoenix.jpeg"},
  { title: "Harry Potter and the Half Blood Prince", author_fname: "J.K.", author_lname: "Rowling", description: "When Dumbledore arrives at Privet Drive one summer night to collect Harry Potter, his wand hand is blackened and shrivelled, but he does not reveal why. Secrets and suspicion are spreading through the wizarding world, and Hogwarts itself is not safe. Harry is convinced that Malfoy bears the Dark Mark: there is a Death Eater amongst them. Harry will need powerful magic and true friends as he explores Voldemort's darkest secrets, and Dumbledore prepares him to face his destiny...", cover: "https://s3.amazonaws.com/shouldreads-dev/harry+potter+half+blood+prince.jpeg"},
  { title: "Harry Potter and the Deathly Hallows", author_fname: "J.K.", author_lname: "Rowling", description: "Dark times have come to Hogwarts. After the Dementors' attack on his cousin Dudley, Harry Potter knows that Voldemort will stop at nothing to find him. There are many who deny the Dark Lord's return, but Harry is not alone: a secret order gathers at Grimmauld Place to fight against the Dark forces. Harry must allow Professor Snape to teach him how to protect himself from Voldemort's savage assaults on his mind. But they are growing stronger by the day and Harry is running out of time...", cover: "https://s3.amazonaws.com/shouldreads-dev/harry+potter+deathly+hallows.jpeg"},

  { title: "The Hobbit", author_fname: "J.R.R.", author_lname: "Tolkien", description: "A great modern classic and the prelude to THE LORD OF THE RINGS Bilbo Baggins is a hobbit who enjoys a comfortable, unambitious life, rarely traveling any farther than his pantry or cellar. But his contentment is disturbed when the wizard Gandalf and a company of dwarves arrive on his doorstep one day to whisk him away on an adventure. They have launched a plot to raid the treasure hoard guarded by Smaug the Magnificent, a large and very dangerous dragon. Bilbo reluctantly joins their quest, unaware that on his journey to the Lonely Mountain he will encounter both a magic ring and a frightening creature known as Gollum.", cover: "https://s3.amazonaws.com/shouldreads-dev/hobbit.jpeg"},
  { title: "The Fellowship of the Ring", author_fname: "J.R.R.", author_lname: "Tolkien", description: "In ancient times the Rings of Power were crafted by the Elven-smiths, and Sauron, the Dark Lord, forged the One Ring, filling it with his own power so that he could rule all others. But the One Ring was taken from him, and though he sought it throughout Middle-earth, it remained lost to him. After many ages it fell into the hands of Bilbo Baggins, as told in The Hobbit. In a sleepy village in the Shire, young Frodo Baggins finds himself faced with an immense task, as his elderly cousin Bilbo entrusts the Ring to his care. Frodo must leave his home and make a perilous journey across Middle-earth to the Cracks of Doom, there to destroy the Ring and foil the Dark Lord in his evil purpose.", cover: "https://s3.amazonaws.com/shouldreads-dev/fellowship+of+the+ring.jpeg"},
  { title: "The Two Towers", author_fname: "J.R.R.", author_lname: "Tolkien", description: "Frodo and his Companions of the Ring have been beset by danger during their quest to prevent the Ruling Ring from falling into the hands of the Dark Lord by destroying it in the Cracks of Doom. They have lost the wizard, Gandalf, in a battle in the Mines of Moria. And Boromir, seduced by the power of the Ring, tried to seize it by force. While Frodo and Sam made their escape, the rest of the company was attacked by Orcs. Now they continue the journey alone down the great River Anduin—alone, that is, save for the mysterious creeping figure that follows wherever they go.", cover: "https://s3.amazonaws.com/shouldreads-dev/two+towers.jpeg"},
  { title: "The Return of the King", author_fname: "J.R.R.", author_lname: "Tolkien", description: "As the Shadow of Mordor grows across the land, the Companions of the Ring have become involved in separate adventures. Aragorn, revealed as the hidden heir of the ancient Kings of the West, has joined with the Riders of Rohan against the forces of Isengard, and takes part in the desperate victory of the Hornburg. Merry and Pippin, captured by Orcs, escape into Fangorn Forest and there encounter the Ents. Gandalf has miraculously returned and defeated the evil wizard, Saruman. Sam has left his master for dead after a battle with the giant spider, Shelob; but Frodo is still alive—now in the foul hands of the Orcs. And all the while the armies of the Dark Lord are massing as the One Ring draws ever nearer to the Cracks of Doom.", cover: "https://s3.amazonaws.com/shouldreads-dev/return+of+the+king.jpeg"},

  { title: "Dune", author_fname: "Frank", author_lname: "Herbert", description: "Here is the novel that will be forever considered a triumph of the imagination. Set on the desert planet Arrakis, Dune is the story of the boy Paul Atreides, who would become the mysterious man known as Muad'Dib. He would avenge the traitorous plot against his noble family--and would bring to fruition humankind's most ancient and unattainable dream. A stunning blend of adventure and mysticism, environmentalism and politics, Dune won the first Nebula Award, shared the Hugo Award, and formed the basis of what it undoubtedly the grandest epic in science fiction.", cover: "https://s3.amazonaws.com/shouldreads-dev/dune.jpeg"},
  { title: "Dune Messiah", author_fname: "Frank", author_lname: "Herbert", description: "With millions of copies sold worldwide, Frank Herbert's magnificent Dune books stand among the major achievements of the human imagination. Set on the desert planet Arrakis -- a world as fully real and rich as our own -- Dune Messiah continues the story of the man Muad'Dib, heir to a power unimaginable, bringing to completion the centuries-old scheme to create a superbeing...", cover: "https://s3.amazonaws.com/shouldreads-dev/dune+messiah.jpeg"},
  { title: "Children of Dune", author_fname: "Frank", author_lname: "Herbert", description: "The desert planet of Arrakis has begun to grow green and lush. The life-giving spice is abundant. The nine-year-old royal twins, possesing their father's supernatural powers, are being groomed as Messiahs.
But there are those who think the Imperium does not need messiahs...", cover: "https://s3.amazonaws.com/shouldreads-dev/children+of+dune.jpeg"},
  { title: "God Emperor of Dune", author_fname: "Frank", author_lname: "Herbert", description: "Millennia have passed on Arrakis, and the oncedesert planet is green with life. Leto Atreides, the son of the world's savior, the Emperor Paul Muad'Dib, is still alive but far from human. To preserve humanity's future, he sacrificed his own by merging with a sandworm, granting him near immortality as God Emperor of Dune for the past 3,500 years.

Leto's rule is not a benevolent one. His transformation has not only made his appearance inhuman, but his morality. A rebellion has risen to oppose the despot's rule, led by Siona, a member of the Atreides family. But Siona is unaware that Leto's vision of a Golden Path for humanity requires her to fulfill a destiny she never wanted or could possibly conceive?", cover: "https://s3.amazonaws.com/shouldreads-dev/god+emperor+of+dune.jpeg"},
  { title: "Heretics of Dune", author_fname: "Frank", author_lname: "Herbert", description: "With more than ten million copies sold, Frank Herbert's magnificent Dune books stand among the major achievements of the human imagination. In this, the fifth and most spectacular Dune book of all, the planet Arrakis--now called Rakis--is becoming desert again. The Lost Ones are returning home from the far reaches of space. The great sandworms are dying. And the children of Dune's children awaken from empire as from a dream, wielding the new power of a heresy called love...", cover: "https://s3.amazonaws.com/shouldreads-dev/heretics+of+dune.jpeg"},
  { title: "Chapterhouse: Dune", author_fname: "Frank", author_lname: "Herbert", description: "The desert planet Arrakis, called Dune, has been destroyed. Now, the Bene Gesserit, heirs to Dune's power, have colonized a green world--and are turning it into a desert, mile by scorched mile.
Here is the last book Frank Herbert wrote before his death. A stunning climax to the epic Dune legend that will live on forever...", cover: "https://s3.amazonaws.com/shouldreads-dev/chapterhouse+dune.jpeg"},
  { title: "Hyperion", author_fname: "Dan", author_lname: "Simmons", description: "On the world called Hyperion, beyond the law of the Hegemony of Man, there waits the creature called the Shrike.  There are those who worship it.  There are those who fear it.  And there are those who have vowed to destroy it.  In the Valley of the Time Tombs, where huge, brooding structures move backward through time, the Shrike waits for them all.  On the eve of Armageddon, with the entire galaxy at war, seven pilgrims set forth on a final voyage to Hyperion seeking the answers to the unsolved riddles of their lives.  Each carries a desperate hope--and a terrible secret.  And one may hold the fate of humanity in his hands.", cover: "https://s3.amazonaws.com/shouldreads-dev/hyperion.jpeg"},
  { title: "Otherland: City of Golden Shadow", author_fname: "Tad", author_lname: "Williams", description: "Surrounded by secrecy, it is home to the wildest dreams and darkest nighmares. Incredible amounts of money have been lavished on it. The best minds of two generations have labored to build it. And somehow, bit by bit, it is claiming the Earth's most valuable resource--its children.", cover: "https://s3.amazonaws.com/shouldreads-dev/otherland1.jpeg"},
  { title: "Otherland: River of Blue Fire", author_fname: "Tad", author_lname: "Williams", description: "Otherland. In many ways it is humankind's most stunning achievement: a private, multidimensional universe built over two generations by the greatest minds of the twenty-first century. But this most exclusive of places is also one of the world's best kept secrets, created and controlled by an organization made up of the world's most powerful and ruthless individuals, a private cartel known—to those who know of their existence at all—as The Grail Brotherhood. Though their purpose in creating Otherland is still a mystery, it may not remain so for long. For they have exacted a terrible price from humanity in the process, and even their highly organized global conspiracy cannot hide the nature of their crimes forever.", cover: "https://s3.amazonaws.com/shouldreads-dev/otherland2.jpeg"},
  { title: "Otherland: Mountain of Black Glass", author_fname: "Tad", author_lname: "Williams", description: "Mountain of Black Glass is the third volume of Tad Williams' highly acclaimed four-book series, Otherland. A truly unique reading experience combining elements of science fiction,fantasy, and techno-thriller, it is a rich epic tale in which virtual reality could prove the key to a whole new universe of possibilities for the entire human race--or become the exclusive domain of the rich and the ruthless as they seek a technological pathway to immortality....", cover: "https://s3.amazonaws.com/shouldreads-dev/otherland3.jpeg"},
  { title: "Otherland: Sea of Silver Light", author_fname: "Tad", author_lname: "Williams", description: "A group of adventurers searching for a cure for comatose children find themselves trapped in a sequence of virtual worlds, the only opponents of a conspiracy of the rich to live forever in a dream. Now, they are forced to make an uneasy alliance with their only surviving former enemy against his treacherous sidekick Johnny Wulgaru, a serial killer with a chance to play God forever.
Few science fiction sagas have achieved the level of critical acclaim-and best-selling popularity-as Tad Williams's Otherland novels. A brilliant blend of science fiction, fantasy, and technothriller, it is a rich, multilayered epic of future possibilities.", cover: "https://s3.amazonaws.com/shouldreads-dev/otherland4.jpeg"},
  { title: "Batman: The Dark Knight Returns", author_fname: "Frank", author_lname: "Miller", description: "Celebrate 30 years of one of the most influential stories ever told in the comics medium with the anniversary edition of the undisputed graphic novel masterpiece BATMAN: THE DARK KNIGHT RETURNS. Writer/artist Frank Miller completely reinvents the legend of Batman in this saga of a near-future Gotham City gone to rot, 10 years after the Dark KnightÕs retirement. Forced to take action, the Dark Knight returns in a blaze of fury, taking on a whole new generation of criminals and matching their level of violence. He is soon joined by a new Robin-a girl named Carrie Kelley, who proves to be just as invaluable as her predecessors. But can Batman and Robin deal with the threat posed by their deadliest enemies, after years of incarceration have turned them into perfect psychopaths? And more important, can anyone survive the coming fallout from an undeclared war between the superpowers-or the clash of what were once the worldÕs greatest heroes?", cover: "https://s3.amazonaws.com/shouldreads-dev/dark+knight+returns.jpeg"},
  { title: "Elephantmen Volume 01: Wounded Animals", author_fname: "Richard", author_lname: "Starkings", description: "Collects ELEPHANTMEN #1-7 They were genetically engineered to be supra-human weapons of mass destruction, but ultimately dismissed collectively as Elephantmen. Hip Flask, Ebony Hide and Obadiah Horn count amongst their number; wounded animals who, despite their differences and origins, must live in the world of man.", cover: "https://s3.amazonaws.com/shouldreads-dev/elephantment1.jpeg"},
  { title: "Ayako", author_fname: "Osamu", author_lname: "Tezuka", description: "Long considered as one of Osamu Tezuka's most political narratives, Ayako is also considered to be one of his most challenging as it defies the conventions of his manga by utilizing a completely original cast and relying solely on historical drama to drive the plot.  Ayako, pulls no punches, and does not allow for gimmicks as science-fiction or fantasy may.  Instead Tezuka weaves together a tale which its core simply focuses on a single family, a family that could be considered a metaphor for a rapidly developing superpower.", cover: "https://s3.amazonaws.com/shouldreads-dev/ayako.jpeg"},
  { title: "Watchmen", author_fname: "Alan", author_lname: "Moore", description: "Considered the greatest graphic novel in the history of the medium, the Hugo Award-winning story chronicles the fall from grace of a group of super-heroes plagued by all-too-human failings. Along the way, the concept of the super-hero is dissected as the heroes are stalked by an unknown assassin.", cover: "https://s3.amazonaws.com/shouldreads-dev/watchmen.jpeg"},
  { title: "The Incal", author_fname: "Alejandro", author_lname: "Jodorowsky", description: "John Difool, a low-class detective in a degenerate dystopian world, finds his life turned upside down when he discovers an ancient, mystical artefact called The Incal. Difool's adventures bring him into conflict with the galaxy's greatest warrior, the Metabaron, and pit him against the awesome powers of the Technopope. These encounters and many more make up a tale of comic and cosmic proportions. Visionary storyteller Jodorowsky's epic mythology and the late Moebius's incredible art blend perfectly for this legendary spiritual space adventure series.", cover: "https://s3.amazonaws.com/shouldreads-dev/incal.png"},
  { title: "From Hell", author_fname: "Alan", author_lname: "Moore", description: "", cover: "https://s3.amazonaws.com/shouldreads-dev/from+hell.jpeg"},
])

shelf_assignments = ShelfAssignment.create([
  { book_id: Book.where(title: "Goosebumps: Welcome to Dead House")[0].id, shelf_id: Shelf.where(title: "Goosebumps")[0].id },
  { book_id: Book.where(title: "Goosebumps: Attack of the Mutant")[0].id, shelf_id: Shelf.where(title: "Goosebumps")[0].id },
  { book_id: Book.where(title: "Goosebumps: The Girl who Cried Monster")[0].id, shelf_id: Shelf.where(title: "Goosebumps")[0].id },
  { book_id: Book.where(title: "Goosebumps: The Night of the Living Dummy II")[0].id, shelf_id: Shelf.where(title: "Goosebumps")[0].id },
  { book_id: Book.where(title: "The Hobbit")[0].id, shelf_id: Shelf.where(title: "Fantasy & Science Fiction")[0].id },
  { book_id: Book.where(title: "The Fellowship of the Ring")[0].id, shelf_id: Shelf.where(title: "Fantasy & Science Fiction")[0].id },
  { book_id: Book.where(title: "The Two Towers")[0].id, shelf_id: Shelf.where(title: "Fantasy & Science Fiction")[0].id },
  { book_id: Book.where(title: "The Return of the King")[0].id, shelf_id: Shelf.where(title: "Fantasy & Science Fiction")[0].id },
  { book_id: Book.where(title: "Dune")[0].id, shelf_id: Shelf.where(title: "Fantasy & Science Fiction")[0].id },
  { book_id: Book.where(title: "Dune Messiah")[0].id, shelf_id: Shelf.where(title: "Fantasy & Science Fiction")[0].id },
  { book_id: Book.where(title: "Children of Dune")[0].id, shelf_id: Shelf.where(title: "Fantasy & Science Fiction")[0].id },
  { book_id: Book.where(title: "God Emperor of Dune")[0].id, shelf_id: Shelf.where(title: "Fantasy & Science Fiction")[0].id },
  { book_id: Book.where(title: "Heretics of Dune")[0].id, shelf_id: Shelf.where(title: "Fantasy & Science Fiction")[0].id },
  { book_id: Book.where(title: "Chapterhouse: Dune")[0].id, shelf_id: Shelf.where(title: "Fantasy & Science Fiction")[0].id },
  { book_id: Book.where(title: "Hyperion")[0].id, shelf_id: Shelf.where(title: "Fantasy & Science Fiction")[0].id },
  { book_id: Book.where(title: "Otherland: City of Golden Shadow")[0].id, shelf_id: Shelf.where(title: "Fantasy & Science Fiction")[0].id },
  { book_id: Book.where(title: "Otherland: River of Blue Fire")[0].id, shelf_id: Shelf.where(title: "Fantasy & Science Fiction")[0].id },
  { book_id: Book.where(title: "Otherland: Mountain of Black Glass")[0].id, shelf_id: Shelf.where(title: "Fantasy & Science Fiction")[0].id },
  { book_id: Book.where(title: "Otherland: Sea of Silver Light")[0].id, shelf_id: Shelf.where(title: "Fantasy & Science Fiction")[0].id },
  { book_id: Book.where(title: "Harry Potter and the Sorceror's Stone")[0].id, shelf_id: Shelf.where(title: "Fantasy & Science Fiction")[0].id },
  { book_id: Book.where(title: "Harry Potter and the Chamber of Secrets")[0].id, shelf_id: Shelf.where(title: "Fantasy & Science Fiction")[0].id },
  { book_id: Book.where(title: "Harry Potter and the Prisoner of Azkaban")[0].id, shelf_id: Shelf.where(title: "Fantasy & Science Fiction")[0].id },
  { book_id: Book.where(title: "Harry Potter and the Goblet of Fire")[0].id, shelf_id: Shelf.where(title: "Fantasy & Science Fiction")[0].id },
  { book_id: Book.where(title: "Harry Potter and the Order of the Phoenix")[0].id, shelf_id: Shelf.where(title: "Fantasy & Science Fiction")[0].id },
  { book_id: Book.where(title: "Harry Potter and the Half Blood Prince")[0].id, shelf_id: Shelf.where(title: "Fantasy & Science Fiction")[0].id },
  { book_id: Book.where(title: "Harry Potter and the Deathly Hallows")[0].id, shelf_id: Shelf.where(title: "Fantasy & Science Fiction")[0].id },
  { book_id: Book.where(title: "Ayako")[0].id, shelf_id: Shelf.where(title: "Comics & Graphic Novels")[0].id },
  { book_id: Book.where(title: "Batman: The Dark Knight Returns")[0].id, shelf_id: Shelf.where(title: "Comics & Graphic Novels")[0].id },
  { book_id: Book.where(title: "Elephantmen Volume 01: Wounded Animals")[0].id, shelf_id: Shelf.where(title: "Comics & Graphic Novels")[0].id },
  { book_id: Book.where(title: "Watchmen")[0].id, shelf_id: Shelf.where(title: "Comics & Graphic Novels")[0].id },
  { book_id: Book.where(title: "The Incal")[0].id, shelf_id: Shelf.where(title: "Comics & Graphic Novels")[0].id },
  { book_id: Book.where(title: "From Hell")[0].id, shelf_id: Shelf.where(title: "Comics & Graphic Novels")[0].id },
  { book_id: Book.where(title: "Harry Potter and the Sorceror's Stone")[0].id, shelf_id: Shelf.where(title: "Harry Potter")[0].id },
  { book_id: Book.where(title: "Harry Potter and the Chamber of Secrets")[0].id, shelf_id: Shelf.where(title: "Harry Potter")[0].id },
  { book_id: Book.where(title: "Harry Potter and the Prisoner of Azkaban")[0].id, shelf_id: Shelf.where(title: "Harry Potter")[0].id },
  { book_id: Book.where(title: "Harry Potter and the Goblet of Fire")[0].id, shelf_id: Shelf.where(title: "Harry Potter")[0].id },
  { book_id: Book.where(title: "Harry Potter and the Order of the Phoenix")[0].id, shelf_id: Shelf.where(title: "Harry Potter")[0].id },
  { book_id: Book.where(title: "Harry Potter and the Half Blood Prince")[0].id, shelf_id: Shelf.where(title: "Harry Potter")[0].id },
  { book_id: Book.where(title: "Harry Potter and the Deathly Hallows")[0].id, shelf_id: Shelf.where(title: "Harry Potter")[0].id },
])

# books = Book.create([
#   { title: "Grapes of Wrath", author_fname: "John", author_lname: "Steinbeck", cover: "https://s3.amazonaws.com/shouldreads-dev/book-438935_960_720.png"},
#   { title: "Ender's Game", author_fname: "Orson Scott", author_lname: "Card", cover: "https://s3.amazonaws.com/shouldreads-dev/book-438935_960_720.png" },
#   { title: "The History of Sexuality, Part I", author_fname: "Michel", author_lname: "Foucault", cover: "https://s3.amazonaws.com/shouldreads-dev/book-438935_960_720.png" },
#   { title: "Madness and Civilization", author_fname: "Michel", author_lname: "Foucault", cover: "https://s3.amazonaws.com/shouldreads-dev/book-438935_960_720.png" },
#   { title: "The Birth of the Clinic", author_fname: "Michel", author_lname: "Foucault", cover: "https://s3.amazonaws.com/shouldreads-dev/book-438935_960_720.png" },
#   { title: "The Order of Things", author_fname: "Michel", author_lname: "Foucault", cover: "https://s3.amazonaws.com/shouldreads-dev/book-438935_960_720.png" },
#   { title: "Archeology of Knowledge", author_fname: "Michel", author_lname: "Foucault", cover: "https://s3.amazonaws.com/shouldreads-dev/book-438935_960_720.png" },
#   { title: "Discipline and Punish", author_fname: "Michel", author_lname: "Foucault", cover: "https://s3.amazonaws.com/shouldreads-dev/book-438935_960_720.png" },
#   { title: "To Kill A Mockingbird", author_fname: "Harper", author_lname: "Lee", cover: "https://s3.amazonaws.com/shouldreads-dev/book-438935_960_720.png" },
#   { title: "All the Light We Cannot See", author_fname: "Anthony", author_lname: "Doer", cover: "https://s3.amazonaws.com/shouldreads-dev/book-438935_960_720.png" },
#   { title: "The River Why", author_fname: "David James", author_lname: "Duncan", cover: "https://s3.amazonaws.com/shouldreads-dev/book-438935_960_720.png" },
#   { title: "A River Runs Through It", author_fname: "Norman", author_lname: "Maclean", cover: "https://s3.amazonaws.com/shouldreads-dev/book-438935_960_720.png" },
#   { title: "The Name of the Wind", author_fname: "Patrick", author_lname: "Rothfuss", cover: "https://s3.amazonaws.com/shouldreads-dev/book-438935_960_720.png" }
# ])
